version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run src/monitor.py --server.enableCORS false --server.maxUploadSize 10000 --server.maxMessageSize 10000" ### for checking as local add local
    ports:
      - "8501:8501"
    volumes:
      - "./src:/usr/src/app/src"

# docker-compose up --build (This command will build the Docker image using the provided Dockerfile and start the container)
# Then can access via http://localhost:8501
# docker-compose exec streamlit /bin/bash (to run tools inside container)<
